### ISSUE TITLE
[question] how to install plugins

### ISSUE THREAD

**Issue by eshepelyuk** [TheRealWaldo/release-it#80]
release-it has number of plugins that could be installed via npm.
Is there a possibility of using those plugins in this action ?

For instance, this one https://github.com/release-it/bumper

**Comment by TheRealWaldo** [comment]
@eshepelyuk sorry for the late reply.  

It is possible, yes!  Just install them in your package.json as you normally would and make sure you've run your `npm install` prior to running this action.

You can see an example of that here:

https://github.com/TheRealWaldo/release-it/blob/master/.github/workflows/release.yml

Our package.json has:

```
  "devDependencies": {
    "@commitlint/cli": "^9.1.2",
    "@commitlint/config-conventional": "^9.1.2",
    "@release-it/bumper": "^1.4.1",
    "@release-it/conventional-changelog": "^1.1.4",
    "@zeit/ncc": "^0.22.3",
    "eslint": "^7.8.1",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4",
    "husky": "^4.2.5",
    "lint-staged": "^10.3.0",
    "prettier": "^2.1.1"
  }
```

**Comment by eshepelyuk** [comment]
Thank you @TheRealWaldo

**Comment by TheRealWaldo** [comment]
I see; for that use case I guess we would need to find a way to compile the plugins in...

What plugins would you need?

**Comment by eshepelyuk** [comment]
Hi, only one mentioned above.

But let me try your approach first, maybe i will make it work.

**Comment by TheRealWaldo** [comment]
@eshepelyuk did you manage to get your use case working?

**Comment by eshepelyuk** [comment]
Hi, 
Unfortunately, I gave up using this action.

**Comment by TheRealWaldo** [comment]
@eshepelyuk Understood; I'll have to look into this because the plugins are loaded dynamically by release-it itself and that makes it hard to compile them in to a github action, but can understand how it would simplify things for a non-node flow!

I'll re-open this as a feature request and see if it's possible.

**Comment by eshepelyuk** [comment]
Thanks @TheRealWaldo !
What about include them all ? And add missing one by one via users' issues ?

**Comment by TheRealWaldo** [comment]
@eshepelyuk that's likely the only way that will be possible; however, getting them even to compile in is a challenge since they're loaded runtime normally.  I'm digging through the release-it source and ncc manuals now to see if there's an easy answer.

**Comment by TheRealWaldo** [comment]
So, there will definitely be more to it than just compiling in the libraries.  The current release-it code runs an explicit require statement to instantiate the plugins, which requires the plugins to be on the file system.

So I see three possible ways forward:

1. Dockerize the whole thing and globally install node, release-it, and all the plugins.  I dislike this, as it greatly slows down the actions and ultimately costs everyone using it more.  If this turns out to be the only option, I would likely maintain two versions of the action.
2. Add an option to select the plugins, and have them downloaded into the dist directory on-demand.  This might work as there is functionality in release-it already that looks in the current working directory for plugins.  But it also might not work.
3. Ask or contribute a change to release-it itself, to allow for injection of the plugins vs. loading them from the filesystem.  This might not fly, but the maintainer there is very active and approachable, so it could be an option.

I suppose there is also minor variations of these options.  I am most partial to exploring #2 myself, but I'm interested in feedback or other ideas.

**Comment by eshepelyuk** [comment]
Thanks for keep working on this. 
Unfortunately I cant help with anything related to nodejs :(.

For me as a simple user, I would like any of the options that could allow me reducing my workflow and remove boilerplate of installing node, installing tool and plugin, manage cache etc.

**Comment by TheRealWaldo** [comment]
@eshepelyuk just wanted to let you know I haven't forgotten about your use case.  

We've faced a number of challenges with dependencies that do not work as expected within GitHubs specific usage, and I am still looking for work-arounds that will still keep the run-time low without having to resort to option 1.

**Comment by eshepelyuk** [comment]
Absolutely no probs. Appreciations for taking this issue so seriously.
